### PR TITLE
Library can now be initialized with a logger

### PR DESCRIPTION
**Pull request by mfilej**
If you have a `logger` object that you would like to log to:

```
Gemonames.client(username: "user", logger: logger)
```

This will log the url and response status code.

### CODE REVIEW

**Comment by ignacy** [comment]
:star:

**Comment by lminaudier** [comment]
:star2:

**Comment by RadekMolenda** [comment]
:star:

**Comment by ChuckJHardy** [comment]
:star:

**Comment by RadekMolenda** [comment]
:star:

**Pull request merged**
